### ISSUE TITLE
After specifing abs path for training data and container name I get the following error:

### ISSUE THREAD

**Issue by dusvyat** [BMW-InnovationLab/BMW-YOLOv4-Training-Automation#18]
When I execute `./run_docker_linux_gpu.sh`

After specifing abs path for training data and container name I get the following error:

`docker: Error response from daemon: Unknown runtime specified nvidia.`

any pointers would be greatly appreciated

**Comment by dusvyat** [comment]
https://github.com/NVIDIA/nvidia-container-runtime

following these steps fixed it :+1:

**Comment by hadikoub** [comment]
The issue is that you don’t have nvidia runtime. Installing nvidia-docker should solve the issue.

**Comment by dusvyat** [comment]
Yep thanks. I reread readme and realised I had missed that part. I'm now getting an error saying n_samples =1 when I try and train using custom data. Trying to debug it but not sure exactly what the issue is. Seems to be coming from the train test split.

**Comment by hadikoub** [comment]
Please can you give more details about the error such as logs or the content of the config files so I can help you.

**Comment by dusvyat** [comment]
This is the exact output I get.

data can be found here, if interested:

https://1drv.ms/u/s!Aq_8IIh0lr1Yi49kFeJP-t5uk6FKvg?e=KcFsNo

Any help would be greatly appreciated!


```
using yolo v4 version
2020-10-31 19:26:07,049 Events Log  : INFO     Creating custom trainings folder
2020-10-31 19:26:07,050 Events Log  : INFO     Checking if all data is valid
2020-10-31 19:26:07,065 Events Log  : INFO     Loading all images
100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.91s/it]
2020-10-31 19:26:08,976 Events Log  : INFO     Loading all labels
100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.88s/it]
2020-10-31 19:26:10,864 Events Log  : INFO     Creating your training folder
2020-10-31 19:26:10,865 Events Log  : INFO     Creating needed folders: weights and config
2020-10-31 19:26:10,866 Events Log  : INFO     Copying yolov4 file to needed location
100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  4.73it/s]
2020-10-31 19:26:11,079 Events Log  : INFO     train.txt and test.txt not found
2020-10-31 19:26:11,079 Events Log  : INFO     Creating train.txt and test.txt in needed location
ValueError: With n_samples=1, test_size=0.19999999999999996 and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.
```

**Comment by hadikoub** [comment]
please can you provide me with the train_config.json
I will try to replicate the error with the provided dataset

**Comment by hadikoub** [comment]
I will try to reproduce the error it seems like the error is coming from the dataset.

**Comment by dusvyat** [comment]
Yes I think so too, let me know if you are able to reproduce the error

**Comment by dusvyat** [comment]
Did you get a chance to have a look?

**Comment by hadikoub** [comment]
I'm really sorry for the delay in response

so after looking very closely at the dataset and after some testing that took some time, it seems that the issue is related to class distribution inside the dataset.
our repo will split test and train set accordingly to each class this will help in creating a test and train data that are well balanced across all classes in your dataset. 
The issue is that inside your dataset you have a lot of classes that are not represented in the labels and when the algorithm is trying to create a test/train-set he raises an error because some classes are not represented in the labels.

I run a dataset analysis to see the classes that may cause the issue and the result I got is:
![Screenshot from 2020-11-17 13-24-27](https://user-images.githubusercontent.com/31547256/99385116-2cd36d80-28d9-11eb-859b-03bd83069bc6.png)
so the classes labeled **under-represented**  are causing the issue
ps: the numbers are linked to labels names provided in train_config.json respectevely
you can solve the problem by removing those classes or increasing images having those classes to balance the data 

you can refer to train_test_split function documentation where the error is raised to get a better understanding of the cause of the issue https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

**Comment by dusvyat** [comment]
Thanks for looking into it.

We were thinking it was due to an issue with train/test split

Since posting I have cleared up the dataset to remove these classes, haven't gotten a chance to run it yet as I have taken a different approach. I have been trying out YOLO V5

I will let you know if I get a chance to rerun.
